" set , as leader command
let mapleader=','

runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()

"syntax configuration
syntax on
filetype plugin indent on

" color themes & light bg
set background=dark

"let g:solarized_termcolors=256
"colorscheme solarized

colorscheme jellybeans

" set a highlight at 100 chars & 120+ to show line wrap goodness
let &colorcolumn="100,".join(range(120,999),",")
" if we want a really bold color column
"highlight ColorColumn cterm=bold ctermbg=234 guibg=#003333

" other options for vim
set nu

" NERDtree options
map <Leader>n :NERDTreeToggle<CR>
let g:nerdtree_tabs_open_on_console_startup = 1

" close vim when only window left is nerdtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" syntastic settings
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs=1

" vim-better-whitespace
" shortcut to strip
nmap <leader><space> :StripWhitespace<CR>
" doesn't seem to hightight on dark backgrounds without this
hi ExtraWhitespace guibg=#990000 ctermbg=red

" vim-airline
set laststatus=2
let g:airline#extensions#csv#enabled = 0

" turn on vim-indent-guides at startup
let g:indent_guides_enable_on_vim_startup = 0

" helpers for vimrc itself
autocmd! bufwritepost .vimrc source ~/.vimrc

" default sw=4 ts=4 sts=4 expandtab
set sw=4 ts=4 sts=4 expandtab

" proper formatting for various file types
" add comment auto add on newline, autowrap and add leader in middle
:set formatoptions+=roc

" Treat JSON files like JavaScript
au BufNewFile,BufRead *.json set ft=javascript

" make Python follow Versity pylintrc
au FileType python setlocal softtabstop=4 tabstop=4 shiftwidth=4 expandtab shiftround autoindent textwidth=99

" Versity C style
au FileType c setlocal softtabstop=8 tabstop=8 shiftwidth=8 noexpandtab shiftround autoindent textwidth=99

" Versity shell style
au FileType sh setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4 autoindent textwidth=99

" In Versity Makefiles, use real tabs, not tabs expanded to spaces
au FileType make setlocal noexpandtab

" Make sure all mardown files have the correct filetype set and setup wrapping
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn,txt} setf markdown

" Pretty YAML files too
autocmd FileType yaml set autoindent shiftwidth=2 softtabstop=2 expandtab wrap linebreak textwidth=90 nolist
