" set , as leader command
let mapleader=','

runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()

"syntax configuration
syntax on
filetype plugin indent on

" other options for vim
set nu

" add shortcut for nerdtree
map <Leader>n :NERDTreeToggle<CR>

"syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" helpers for vimrc itself
autocmd! bufwritepost .vimrc source ~/.vimrc
